/**
 * PDF Engine v1.0
 * Generates professional clinical appeal layouts
 */

exports.generateAppealHTML = (lead, appealText) => {
    return `
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; line-height: 1.5; }
        .header { border-bottom: 2px solid #2d3748; padding-bottom: 20px; margin-bottom: 30px; }
        .hospital-name { font-size: 24px; font-weight: bold; color: #2d3748; }
        .document-type { font-size: 14px; color: #718096; text-transform: uppercase; letter-spacing: 1px; }
        .meta-table { width: 100%; margin-bottom: 30px; font-size: 14px; }
        .meta-table td { padding: 5px 0; }
        .meta-label { font-weight: bold; width: 150px; }
        .content { white-space: pre-wrap; font-size: 14px; }
        .footer { margin-top: 50px; font-size: 12px; color: #a0aec0; border-top: 1px solid #edf2f7; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="hospital-name">⚡ CMS COMPLIANCE BRIDGE</div>
        <div class="document-type">Official Clinical Appeal & Regulatory Reconsideration</div>
    </div>
    
    <table class="meta-table">
        <tr><td class="meta-label">PATIENT:</td><td>${lead.username || lead.user}</td></tr>
        <tr><td class="meta-label">CLAIM ID:</td><td>${lead.id}</td></tr>
        <tr><td class="meta-label">PAYER:</td><td>${lead.insurance_type}</td></tr>
        <tr><td class="meta-label">REGULATORY REF:</td><td>CMS-0057-F / Section 422.568</td></tr>
    </table>

    <div class="content">
${appealText}
    </div>

    <div class="footer">
        This document was generated by an automated clinical advocacy system. 
        For inquiries regarding regulatory compliance, contact the Compliance Officer.
    </div>
</body>
</html>
    `.trim();
};
