const PDFDocument = require('pdfkit');

export default async function handler(req, res) {
    if (req.method !== 'POST') return res.status(405).end();

    const { appealText, claimId, clinicalResearch, regulatoryCitations } = req.body;

    if (!appealText) {
        return res.status(400).json({ error: 'appealText is required' });
    }

    try {
        const doc = new PDFDocument({ margin: 50, size: 'LETTER' });
        
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=Appeal_Package_${claimId || 'Draft'}.pdf`);

        doc.pipe(res);

        // --- PAGE 1: THE FORMAL APPEAL ---
        doc.fontSize(18).text('FORMAL MEDICAL APPEAL', { align: 'center' });
        doc.moveDown();
        doc.fontSize(9).text(`Generated by CMS Compliance Bridge v2.0 | HIPAA-Compliant Gateway`, { align: 'right' });
        doc.moveDown(2);

        doc.fontSize(11).text(appealText, {
            align: 'left',
            lineGap: 4
        });

        // --- PAGE 2: CLINICAL EVIDENCE (If provided) ---
        if (clinicalResearch) {
            doc.addPage();
            doc.fontSize(16).text('EXHIBIT A: CLINICAL EVIDENCE SUPPORT', { align: 'left' });
            doc.moveDown();
            doc.fontSize(10).text('The following peer-reviewed research findings support the medical necessity of the requested procedure:', { oblique: true });
            doc.moveDown();
            
            doc.fontSize(12).text(clinicalResearch.title, { underline: true });
            doc.moveDown(0.5);
            doc.fontSize(11).text(clinicalResearch.snippet, { lineGap: 3 });
            doc.moveDown();
            doc.fontSize(9).fillColor('blue').text(`Full Source: ${clinicalResearch.url}`, { link: clinicalResearch.url });
        }

        // --- PAGE 3: REGULATORY CITATIONS ---
        doc.addPage();
        doc.fillColor('black').fontSize(16).text('EXHIBIT B: REGULATORY COMPLIANCE', { align: 'left' });
        doc.moveDown();
        doc.fontSize(11).text('This appeal is submitted under the mandatory transparency and interoperability requirements of the CMS-0057-F Interoperability and Prior Authorization Final Rule.', { lineGap: 3 });
        doc.moveDown();
        doc.text('Key Mandates Cited:', { bold: true });
        doc.list([
            'CMS-0057-F Section 4.1: Requirement for actionable, granular denial reasons via FHIR API.',
            'CMS-0057-F Section 4.2: Mandatory decision windows (72h Urgent / 7d Standard).',
            'Transparency in Coverage: Payer must provide specific medical policy cross-references.'
        ]);

        doc.end();
    } catch (error) {
        console.error('PDF Engine Error:', error.message);
        res.status(500).json({ error: 'Failed to assemble clinical package' });
    }
}
