const PDFDocument = require('pdfkit');

export default async function handler(req, res) {
    if (req.method !== 'POST') return res.status(405).end();

    const { appealText, claimId } = req.body;

    if (!appealText) {
        return res.status(400).json({ error: 'appealText is required' });
    }

    try {
        const doc = new PDFDocument({ margin: 50 });
        
        // Set headers for PDF download
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=Appeal_${claimId || 'Draft'}.pdf`);

        doc.pipe(res);

        // Add Content
        doc.fontSize(20).text('Medical Appeal Letter', { align: 'center' });
        doc.moveDown();
        doc.fontSize(10).text(`Generated by CMS Compliance Bridge on ${new Date().toLocaleDateString()}`, { align: 'right' });
        doc.moveDown(2);

        doc.fontSize(12).text(appealText, {
            align: 'left',
            lineGap: 5
        });

        doc.end();
    } catch (error) {
        console.error('PDF Generation Error:', error.message);
        res.status(500).json({ error: 'Failed to generate PDF' });
    }
}
